"""empty message

Revision ID: 49b1f7b30811
Revises: a820a0567313
Create Date: 2019-01-28 16:31:58.992213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b1f7b30811'
down_revision = 'a820a0567313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expedition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=255), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('frame_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=255), nullable=True),
    sa.Column('temperature_id', sa.Integer(), nullable=True),
    sa.Column('expedition_date', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['frame_id'], ['frame.id'], ),
    sa.ForeignKeyConstraint(['temperature_id'], ['temperature.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expedition_timestamp'), 'expedition', ['timestamp'], unique=False)
    op.add_column('strain', sa.Column('expedition_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'strain', 'expedition', ['expedition_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strain', type_='foreignkey')
    op.drop_column('strain', 'expedition_id')
    op.drop_index(op.f('ix_expedition_timestamp'), table_name='expedition')
    op.drop_table('expedition')
    # ### end Alembic commands ###
