"""empty message

Revision ID: bcc44ebf4af8
Revises: 1ce0c8f62b74
Create Date: 2019-01-27 03:08:42.062924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc44ebf4af8'
down_revision = '1ce0c8f62b74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strain', sa.Column('sample_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'strain', 'sample_type', ['sample_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strain', type_='foreignkey')
    op.drop_column('strain', 'sample_type_id')
    # ### end Alembic commands ###
